### ISSUE TITLE
TypeError Illegal offset type in isset or empty in Backend Modul

### ISSUE THREAD

**Issue by wowaTYPO3** [fnagel/t3extblog#270] opened 2024-01-25 19:38 UTC
Posts view:
![2024-01-25_20-37-04](https://github.com/fnagel/t3extblog/assets/343511/7d3ac189-e215-48a4-ae7c-a55755d02b5f)

**Comment by fnagel** [comment] 2024-01-26 08:32
@wowaTYPO3 I've pushed a fix, would you mind to do a quick test if it works? Not quite sure, as I was not able to reproduce it.

It's just a small change, you can do manually in your setup: cc403527c62b97d49db6ffc10983730eb8beea74

**Closed** 2024-02-06 17:03 UTC
Labels: bug
