### ISSUE TITLE
Translated post doesn't have categories

### ISSUE THREAD

**Issue by DavidKang** [fnagel/t3extblog#138] opened 2016-07-07 09:27 UTC
Hi,

Translating a post I can not assign a category to post translated, and the database appears the post without a category and in the table (tx_t3blog_post_cat_mm) there is no record.
Because of the above, the translated post does not appear in the frontend when filtering by a category.

I'm using t3extblog 2.2.1 and typo3 7.6.4 version.

![captura de pantalla 2016-07-07 a las 10 25 37](https://cloud.githubusercontent.com/assets/1212806/16648721/40e95bd0-442d-11e6-99d8-65066f675c54.png)

**Comment by fnagel** [comment] 2016-07-07 16:59
Right, there is no option to add categories to a localized post. Those are inherited from the original post. This is by design.

Anyway, you should be able to see the posts when filtered by category. Did you translate your categories?

**Comment by fnagel** [comment] 2016-07-07 22:48
Confirmed the issue in 7.6 but this should be a problem in 6.2 too. 

Here is one of many tickets (incl. a workaround by Dmitry Dulepov for 6.2): https://forge.typo3.org/issues/57272

I'm working on a fix for 7.6 and above.

**Comment by fnagel** [comment] 2016-07-09 13:41
This is based on my current dev master so you might need to adopt those changes manually. Please test and give feedback!

[patch.zip](https://github.com/fnagel/t3extblog/files/355575/patch.zip)

**Comment by DavidKang** [comment] 2016-07-11 07:27
Thanks, this work for me.

**Comment by fnagel** [comment] 2016-07-11 07:32
Nice, thanks for the feedback. Will be part of the next release.

**Comment by fnagel** [comment] 2016-11-16 13:38
Reopen, as closed accidentally by pushing a non public branch.

**Closed** 2017-07-24 09:19 UTC
Labels: bug
