### ISSUE TITLE
No beautiful-RealURL-hyperlinks in notification mails

### ISSUE THREAD

**Issue by Longjogger** [fnagel/t3extblog#247] opened 2021-06-17 14:49 UTC
Hi everybody,

I am using T3extblog 4.2 with TYPO3 8.7.32.

The RealURL function works fine in the webfrontend and in the first mails when I registered myself for new articles and comments.
But when I am sending an email with a new blog article or a new comment, then the hyperlinks are not beauftiful:
> a new post has been released on Blog:
> https://URL/index.php?id=3991&amp;L=0&amp;tx_t3extblog_blogsystem[post]=9&amp;tx_t3extblog_blogsystem[day]=17&amp;tx_t3extblog_blogsystem[month]=06&amp;tx_t3extblog_blogsystem[year]=2021&amp;tx_t3extblog_blogsystem[action]=show&amp;tx_t3extblog_blogsystem[controller]=Post&amp;cHash=d230e8b5f55a0e25aa74c0f1882bf193
> 
> 
> You can manage your subscription by using this link:
> https://URL/index.php?id=4045&amp;L=0&amp;tx_t3extblog_subscriptionmanager[code]=743dad8c15896686e882b4c0a70e66c0&amp;tx_t3extblog_subscriptionmanager[action]=list&amp;tx_t3extblog_subscriptionmanager[controller]=BlogSubscriber&amp;cHash=1633023c845b5b870255b68a107ccced

How I can change this mistake?

Best regards!

**Comment by fnagel** [comment] 2021-06-21 12:55
Looks like RealUrl does not kick in. Can you show me where and how you included the TypoScript?

Did you add the 'T3Extblog: additional RealUrl config' TS file? See https://github.com/fnagel/t3extblog/blob/4.x/Documentation/Configuration/Index.rst#realurl
Are you manually changing the TS config? If so, did you update the backend TS? See https://github.com/fnagel/t3extblog/blob/4.x/Configuration/TypoScript/setup.txt#L397-L399

**Comment by Longjogger** [comment] 2021-06-22 13:40
Well, but when I subscribe the blog RealURL kick in...

Yes, I add the 'T3Extblog: additional RealURL config' as a static template.
But this alone works not, because we work with a realurlconf.php-file created by an agency. So I add this to our realurlconf.php: https://github.com/fnagel/t3extblog/blob/4.x/Classes/Hooks/RealUrl.php#L50-#L201
So RealURL works on website and when I when I subscribe the Blog... But links in other mails are working not...

**Comment by fnagel** [comment] 2021-06-28 16:04
The causing issue is the context: frontend or backend

Yes, the TS alone is not enough, you will need the realurl config, but that seems to work in general. 

My guess is that the mails in the backend context (e.g. comment with subscription not approved or SPAM) is enabled from the BE module, triggering an email. This could be caused by not using the frontend link VH within the emails or TS is not fully available.

Please double check if the TS has been changed and not added to `module.tx_t3extblog`. Try adding the TS on root rather than on a subpage (with additional TS template). Check if the FE uri VH is in use.

**Comment by fnagel** [comment] 2021-12-09 23:21
Any feedback on this issue?

**Comment by fnagel** [comment] 2022-01-28 00:07
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Closed by fnagel** 2022-01-28 00:07 UTC
Labels: bug, question, needs feedback
