### ISSUE TITLE
Exception when adding comment with spam settings changed

### ISSUE THREAD

**Issue by romaneberle** [fnagel/t3extblog#53] opened 2015-05-06 10:01 UTC
in TYPO3 6.2.10 with t3extblog v1.0.2-dev as of 2015-05-05, TYPO3 says:

````#1249479819: The object of type "Tx_T3extblog_Domain_Model_Comment" given to update must be persisted already, but is new.````

when adding a comment with (as it seems) any of the spam-settings changed, e.g. like this:

````plugin.tx_t3extblog.settings.comments.spamCheck.enable = 0````
or
````plugin.tx_t3extblog.settings.comments.spamCheck.isHumanCheckbox = 0````

here's some backtrace output (shortened):
````
20 TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager::update(Tx_T3extblog_Domain_Model_Comment)
19 TYPO3\CMS\Extbase\Persistence\Repository::update(Tx_T3extblog_Domain_Model_Comment)
18 Tx_T3extblog_Service_NotificationService::notifySubscribers(Tx_T3extblog_Domain_Model_Comment)
17 Tx_T3extblog_Service_NotificationService::processCommentAdded(Tx_T3extblog_Domain_Model_Comment)
````
...

possible bugfix:
in Classes/Service/NotificationService.php, line 320:
replace:
````
$this->objectManager->get('Tx_T3extblog_Domain_Repository_CommentRepository')->update($comment);
````
with:
````
$this->objectManager->get('Tx_T3extblog_Domain_Repository_CommentRepository')->add($comment);
````

...but i seriously doubt this is the correct way... ;-)

**Comment by romaneberle** [comment] 2015-05-06 13:09
CORRECT BUGFIX:
in Classes/Controller/CommentController.php, line 144:

/* @var $persistenceManager Tx_Extbase_Persistence_Manager */
//$persistenceManager = $this->objectManager->get('Tx_Extbase_Persistence_Manager');
$objectManager = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Extbase\Object\ObjectManager');
$persistenceManager = $objectManager->get('TYPO3\\CMS\\Extbase\\Persistence\\Generic\\PersistenceManager');
$persistenceManager->persistAll();

please someone commit this.

**Comment by fnagel** [comment] 2015-05-14 12:49
I doubt your second bugfix will change anything. You just changed the classname to the "new", namespaced one. Anyway, the same class will be created, regardless of the change. In TYPO3 7.x this wont work without the legacy compat layer but 7.x is not supported at the moment.

Your first proposed change makes much more sense. I will check this asap.

**Comment by romaneberle** [comment] 2015-05-14 16:11
well, I applied the first one and got another exception, then the second one and it was gone. in other words: it changed the extension from unusabe to usable.

**Comment by fnagel** [comment] 2015-05-14 17:55
Well, your second fix does plain nothing when using TYPO3 6.0.0-6.2.x. Perhaps a cache issue? 

I noticed your above posted TS settings does not exist. There is no ````settings.comments.spamCheck```` config but a ````settings.blogsystem.comments.spamCheck````.

Anyway, even with the correct settings to disable SPAM check I can't reproduce your issue.

When looking at your stacktrace I do not understand whats happening, as the comment is already registered at the very moment, see https://github.com/fnagel/t3extblog/blob/master/Classes/Controller/CommentController.php#L142-L148

Can you give me the whole stacktrace and your whole TS config (or just the overwritten parts)?

**Comment by fnagel** [comment] 2015-06-19 17:30
Any feedback on this issue?

**Comment by fnagel** [comment] 2015-07-29 10:49
Closed as no feedback was given. Please reopen if needed.

**Closed by fnagel** 2015-07-29 10:49 UTC
Labels: bug, needs feedback
