### ISSUE TITLE
Bug: Author field is not saved on creating new blogposts

### ISSUE THREAD

**Issue by Moongazer** [fnagel/t3extblog#131] opened 2016-05-24 21:48 UTC
It's just a tiny bug: the field for "Author" is not saved if a new blog post is created. Only the second saving process (update) saves the correct value.

**Reproduce:**
1) You need a second backend-user
2) Create a new blog post inside the storage folder
3) Fill the required fields (Title, Category), and select the other backend-user as Author (not the current user which you are logged in as)
4) Click Save
5) After the page is reloaded, you will see that your current user is the Author, not the selected one

Can someone confirm this behaviour?

**Environment:**
TYPO3 v7.6.6
T3ExtBlog v2.2.1
PHP v5.6
MySQL v5.6

**Comment by fnagel** [comment] 2016-05-26 11:31
Thanks for the bug report -- I will check this soon and provide a fix if needed.

**Comment by fnagel** [comment] 2016-05-26 11:45
Bug confirmed.

**Comment by fnagel** [comment] 2016-05-26 12:32
This is due to the author field is used as cruser_id for the post records. So, you choose user x but you're logged in as user y and when saving first time, the cruser_id config will set the author field to your current user (user y) instead of user x. 

I've added a proper cruser_id field to SQL and changed the TCA. create user and uuthor should be separated properties so this old t3blog configuration should be fixed. I've added an EM update script to copy the author values to the new field.

Please test and give feedback!

**Closed by fnagel** 2016-05-26 12:32 UTC
Labels: bug

**Comment by Moongazer** [comment] 2016-05-26 18:06
Test successful, issue solved in current 3.0.0-dev, thanks :-)
