### ISSUE TITLE
New post changes sorting of content elements of the last post

### ISSUE THREAD

**Issue by macsvenne** [fnagel/t3extblog#162] opened 2017-01-04 07:49 UTC
I´m trying to implement t3extblog on a TYPO3 installation with version 6.2.29, PHP 5.6 and MySQL 5.0.11. It works fine except for changing the sorting (see screenshots). 1.x is the first post, 2.x is the new post.

![t3extblog-sorting-before](https://cloud.githubusercontent.com/assets/24910497/21634905/b0ea01b2-d25a-11e6-94c1-4f7dca85a0fd.gif)

![t3extblog-sorting-after](https://cloud.githubusercontent.com/assets/24910497/21634906/b33aff8e-d25a-11e6-98d5-6f7481764a3d.gif)

**Comment by fnagel** [comment] 2017-01-06 17:04
Not sure if I really understand what's happening here. From what I see I would say after adding the second post the sorting of the first one is reversed. Can you explain what you did step by step?

Content elements should be edited within the blog post record itself (using the inline editing mode TYPO3 provides). Best way to do so is using the BE module this extension provides but editing post records directly using the list module is fine too.

**Comment by macsvenne** [comment] 2017-01-16 14:52
You are right. First I created a post with 3 content elements, named 1.1, 1.2 and 1.3. The post started with 1.1 and so on. After that I created a post with 3 content elements, named 2.1, 2.2 and 2.3. This post changed the order of the first post to 1.3, 1.2 and 1.1

I created the posts via the t3extblog BE module. Once I placed the post storage outside of the website file structure, the order was correct. This is a very strange behaviour.

**Comment by fnagel** [comment] 2017-01-19 11:05
>Once I placed the post storage outside of the website file structure, the order was correct. 

Can you add a  screenshot for this?

There is nothing special about how t3extblog handles content records for posts. I guess the behavior  you are noticing is due to TYPO3 wants to order all records of the same type no matter what. Seems like this is how inline records are handled by default.

Not sure if there is something we can do against that, but as mentioned, this should be no problem for rendering in FE. I'm open to suggestions how to fix this and will try to come up with something.

Workaround:
This TS config snippet will hide tt_content records in list module when configuring your sys folder as module "t3blog" (page properties): https://github.com/fnagel/t3extblog/blob/master/Configuration/TypoScript/pageTsConfig.ts#L18-L21

**Comment by fnagel** [comment] 2017-01-27 22:49
>  This issue is not a problem on BE level. It is about re-ordering the content elements also in the FE.

That sounds very strange to me. Never experienced something like that before. Are you sure this isn't a side effect of something else? I would recommend trying to reproduce this in a fresh installation with minimal changes. Another option is using the introduction package.

**Comment by macsvenne** [comment] 2017-02-15 15:04
Maybe it´s a side effect. I had TemplaVoila in mind, but a test with an empty installation had the same issues.

**Comment by fnagel** [comment] 2017-07-10 07:57
Any feedback on this issue?

**Comment by fnagel** [comment] 2017-07-24 09:34
@macsvenne Any feedback on this one? Did you figure out why this issue occurs?

You might want to try the latest master branch!

**Comment by fnagel** [comment] 2017-08-12 10:37
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Closed by fnagel** 2017-08-12 10:37 UTC
Labels: needs feedback, question
