### ISSUE TITLE
RenderContentViewhelper: No dataProcessors called for CE in TYPO3 >= 7.4

### ISSUE THREAD

**Issue by pvanhemmen** [fnagel/t3extblog#92] opened 2015-10-08 21:29 UTC
I encountered an issue with fluid content elements (which also could affect other integrations). In TYPO3 7.4 dataProcessing for media galleries was introduced: https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/7.4/Feature-67663-IntroduceDataProcessorForMediaGalleries.html

Fluid Styled Content makes heavy use of this concept and uses the generated content in its templates:

![dataprocessing](https://cloud.githubusercontent.com/assets/715022/10364837/0633e32e-6dbf-11e5-8bee-6a8eae91bdd1.png)

In t3extblog these processors are never called for inline content elements within blogposts. Therefore all media (images/movies) added in fluid styled content textmedia elements are never rendered for content elements inside blogposts.

The issue is that the viewhelper `RenderContentViewhelper` used in t3extblog basically fetches the contents from the database without executing any processors. For testing purposes I tried the RenderViewHelper provided by vhs, which works. I think the difference is how it fetches the tt_content records:

```$html = $GLOBALS['TSFE']->cObj->cObjGetSingle('RECORDS', $conf);```

This ensures all configurated processores etc. are called as the content is routed through the necessary classes. See also: https://github.com/FluidTYPO3/vhs/blob/master/Classes/ViewHelpers/Content/AbstractContentViewHelper.php#L242.

**Comment by fnagel** [comment] 2015-10-08 22:24
I'm a little confused. What "Fluid Styled Content" do we talk about? EXT:fluidcontent_core (FluidTYPO3) or EXT:fluid_styled_content (Core extension since 7.5.0)? Both?

**Comment by fnagel** [comment] 2015-10-08 23:07
This could be changed but I'm not sure if this will have some impact on some installations. I experimented a lot to have proper rendering of the elements. We'll see...

I've pushed a proposed change. Will need more testing in 6.2 and multilingual installations in both branches. Please give feedback if the issue is fixed by this change.

**Comment by pvanhemmen** [comment] 2015-10-17 06:37
The issue is fixed this change and everything works as expected. Will setup another installation with 6.2 and do some testing there. Will open new issues if I encounter problems.

**Closed** 2015-10-17 06:38 UTC
Labels: bug, needs feedback
